### ISSUE TITLE
Corregir TP #1: No implementa máquina de estados.

### ISSUE THREAD

**Issue by josemariasola** [lelenavarro/navarroSSL#1]
- Como se estableció en clase, el TP debe implementar una máquina de estado, haciendo explícita sus transiciones y estados.
- Cual es la máquina de estado?
- Como se implementa el estado actual?
- Como se implementan las transiciones?
- Las cadenas y caracteres son diferentes, deben tener diferentes ramas de análisis, por ejemplo “a' es válido?

**Comment by mricagno** [comment]
Se agrega:
. Manejo de secuencia de escape
. Implementación de estados para manejar el tratado de comentarios,literales cadena y caracteres
