### ISSUE TITLE
Corregir TP #2: Modelar estados intermedios para comentarios y Abstraer stack.

### ISSUE THREAD

**Issue by josemariasola** [lelenavarro/navarroSSL#2]
- Implementar estados “posible comienzo de comentario” y “posible salida de comentario”, no utilizar aux y ungetc. Parte del pedido en clase es que sea una máquina de estado, no otro tipo de programa.
- Analizar comentarios de una sola línea // como este.
- Desarollar Push y Pop: declararlas en Stack.h e implementarlas en Stack.c

**Comment by mricagno** [comment]
Se agrega:
. El manejo del stack mediante las funciones Push y Pop (definidas en Stack.h y Stack.c)
. Nuevos estados intermedios para el tratamiento de comentarios
